BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[User] ADD [currency] NVARCHAR(1000) NOT NULL CONSTRAINT [User_currency_df] DEFAULT 'TRY',
[language] NVARCHAR(1000) NOT NULL CONSTRAINT [User_language_df] DEFAULT 'tr',
[phone] NVARCHAR(1000);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
